// packages/react/src/editor.tsx
import { useEffect, useRef } from 'react';
import { OpenRichEditor, isClient } from '@openrich/core';
import type { EditorProps } from './types';
import '@openrich/core/src/theme/variables.css';

export function Editor({
  content,
  extensions,
  editable = true,
  onUpdate,
  onFocus,
  onBlur,
  locale,
  theme = 'system',
  placeholder,
}: EditorProps) {
  const editorRef = useRef<OpenRichEditor | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  // Initialize editor on mount
  useEffect(() => {
    if (!isClient || !containerRef.current) return;

    const editor = new OpenRichEditor({
      content,
      extensions,
      editable,
      locale,
      theme,
      placeholder,
      onUpdate,
      onFocus,
      onBlur,
    });

    containerRef.current.appendChild(editor.tiptapEditor.view.dom);
    editorRef.current = editor;

    return () => {
      editor.destroy();
      editorRef.current = null;
    };
  }, []);

  // Sync editable prop
  useEffect(() => {
    editorRef.current?.setEditable(editable);
  }, [editable]);

  // Sync theme prop
  useEffect(() => {
    editorRef.current?.setTheme(theme);
  }, [theme]);

  // Sync locale prop
  useEffect(() => {
    if (locale) editorRef.current?.setLocale(locale);
  }, [locale]);

  if (!isClient) {
    return <div data-openrich-editor data-theme={theme} />;
  }

  return <div ref={containerRef} />;
}

// packages/solid/src/editor.tsx
import { createEffect, onCleanup, onMount } from 'solid-js';
import { OpenRichEditor, isClient } from '@openrich/core';
import type { EditorProps } from './types';
import '@openrich/core/src/theme/variables.css';

export function Editor(props: EditorProps) {
  let containerRef: HTMLDivElement | null = null;
  let editor: OpenRichEditor | null = null;

  onMount(() => {
    if (!isClient || !containerRef) return;
    editor = new OpenRichEditor({
      content: props.content,
      extensions: props.extensions,
      editable: props.editable,
      locale: props.locale,
      theme: props.theme ?? 'system',
      placeholder: props.placeholder,
      onUpdate: props.onUpdate,
      onFocus: props.onFocus,
      onBlur: props.onBlur,
    });
    containerRef.appendChild(editor.tiptapEditor.view.dom);
  });

  onCleanup(() => {
    editor?.destroy();
    editor = null;
  });

  createEffect(() => {
    editor?.setEditable(props.editable ?? true);
  });

  createEffect(() => {
    editor?.setTheme(props.theme ?? 'system');
  });

  createEffect(() => {
    if (props.locale) editor?.setLocale(props.locale);
  });

  if (!isClient) {
    return <div data-openrich-editor data-theme={props.theme ?? 'system'} />;
  }

  return <div ref={(el) => { containerRef = el }} />;
}
